version: '3.4'

services:
  picturedatabase-thumbnail:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      - "443"
  

  picturedatabase-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50001:80"
      - "443"
     

  picturedatabase-greyscale:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      - "443"


  

  picturedatabase-website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - REACT_APP_API=http://localhost:50001/
      - REACT_APP_IMAGEFOLDERPATH=/usr/share/picturedb
    ports:
      - "50000:80"
      - "443"
    
